apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.secret.mongoUsername | toString | b64enc }}
  MONGO_PASSWORD: {{ .Values.secret.mongoPassword | toString | b64enc }}