name: Database Pipeline

on:
  push:
    paths:
      - 'helm/templates/database/**'
      - 'helm/templates/configmap.yaml'
      - 'helm/templates/secret.yaml'
      - 'helm/values.yaml'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install Helm
        run: |
          curl -fsSL https://get.helm.sh/helm-v3.20.2-linux-amd64.tar.gz -o helm.tar.gz
          tar -zxvf helm.tar.gz
          mkdir -p ~/.local/bin
          mv linux-amd64/helm ~/.local/bin/helm
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Deploy database with Helm
        run: |
          helm upgrade --install major-assignment ./helm \
            --namespace default \